### ISSUE TITLE
Unknown keyword BCCON

### ISSUE THREAD

**Issue by keileg** [daavid00/pyopmcsp11#6]
When trying to run the specifications given in `csp11a.txt`, I get an error message `Error: Unknown keyword: BCCON`. 

Running `csp11b.txt` is not a problem. 

My version of flow is 2023.04 - do I need to use a newer one (if so, built from source, I presume)?

**Comment by daavid00** [comment]
Hei,
I refer you to @totto82 reply to the same issue.
https://github.com/Simulation-Benchmarks/11thSPE-CSP/issues/18

**Comment by keileg** [comment]
Got it. Thanks.
